{{- if and (.Capabilities.APIVersions.Has "jenkins.io/v1/Release") (hasKey .Values.jx "releaseCRD") (.Values.jx.releaseCRD)}}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-05-06T13:23:10Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: v.behar@free.fr
      name: Vincent Behar
    branch: master
    committer:
      email: v.behar@free.fr
      name: Vincent Behar
    message: |
      fix: use helm chart api v1

      so that the chart can also be used with helm v2, in jx v2
    sha: 6067c2bf73ac001a4cce6c46471c900f9ac5d753
  gitHttpUrl: https://github.com/jenkins-x/lighthouse-telemetry-plugin
  gitOwner: jenkins-x
  gitRepository: lighthouse-telemetry-plugin
  name: '{{ .Chart.Name }}'
  version: 0.0.2
status: {}
 
{{- end }}
